### ISSUE TITLE
Issue in installing pip

### ISSUE THREAD

**Issue by Nelu-LK** [McKibbin-Software-Group/issues#5]
Hi Geoff,

I was trying to install pip on windows and having troubles in the installation process. It says pip has been successfully installed but it does not return any packages. I have attached a document with screenshots for your perusal please. Could you kindly assist me in resolving this issue please? Many thanks for your support.

Best Regards,
Nelu
[Pip Installation Issue.docx](https://github.com/McKibbin-Software-Group/issues/files/12313032/Pip.Installation.Issue.docx)

**Comment by shuetrim** [comment]
Hi Nelu,

Thanks for putting together the clear documentation showing your installation experience. I think you just need to complete the next steps. 

The next steps should be to use pip to install the packages so they show up in the listing.

Try the following:

```
> pip install pandas
```

That should install the pandas package.

If that does not work, try running pip via python:

```
> py -m pip install pandas
```
Assuming one of those steps works, you then need to download the gcubed package from the documentation website (or the direct link is just below):

[Download for version 1.0.3](https://drive.google.com/uc?export=download&id=1QjTYxp-lkSaoEo_0OQ3PD6F5BGVLJ7NK)

Once downloaded, go to the command prompt in the same directory as the downloaded file and use pip to install that file:

```
> pip install gcubed-1.0.3-py3-none-any.whl
```

If you want to speak with me while doing so, call my mobile (0402 422 377) and we can quickly troubleshoot things before the tutorial this morning.

Regards

Geoff

**Comment by Nelu-LK** [comment]
Hi Geoff,

Thank you for your detailed explanation. I tried the steps but again struggling at installing gcubed file using pip. I have attached the screenshots also please. Are you available to talk at this time or is there any other convenient time for you? Many thanks for your support.
[Pip Installation Issue_2.docx](https://github.com/McKibbin-Software-Group/issues/files/12318472/Pip.Installation.Issue_2.docx)

Best Regards
Nelu

**Comment by shuetrim** [comment]
Jump on zoom now.
https://us06web.zoom.us/j/6376647858?pwd=Y1NCeTRIajlLNVNqS0N3VnZRSnpqdz09

Geoff

**Comment by shuetrim** [comment]
Also, 2 problems seem to be happening:

1. remember the `-m` in the command:

```
py -m pip install gcubed-1.0.3-py3-none-any.whl
```

Second, make sure you current directory where you are running the command is the one that contains the gcubed-1.0.3-py3-none-any.whl file. It looks like you are in the root directory of your C drive but the gcubed file is in a subdirectory of the python installation.

**Comment by Nelu-LK** [comment]
Hi Geoff,

Thank you for your assistance in resolving the pip installation issue last week. I have downloaded the teaching model and when I run the example.py file, I get the error **AttributeError: module 'gcubed' has no attribute 'now'**

Also there was another example file which I tried to run which gave the following error.
ModuleNotFoundError: No module named 'gcubed.runners.simulation_runner'

I have attached a screenshots as well for your reference please. Could you kindly advise on resolving these errors, please?

Many Thanks & Best Regards
Nelu
[Error in Running the Example File.docx](https://github.com/McKibbin-Software-Group/issues/files/12360229/Error.in.Running.the.Example.File.docx)

**Comment by shuetrim** [comment]
Hi Nelu,

This is one of those situations where it can hurt to be on the bleeding edge of development. Just 2 days ago, I updated the version of python gcubed from 1.0.3 to 1.0.5. That update brings a number of improvements and the examples have been altered to demonstrate the new features, like the simulation runner.

It looks to me as though you are using Python Gcubed 1.0.3, with a download of the teaching model from the last day or so that includes changes relating to Python 1.0.5.

To bring things back into alignment, you have two options. 

## First option: upgrade to the new python gcubed package

Just download the new version of python gcubed from [the documentation site](https://documentation.gcubed.com/environment_setup/) and use pip to uninstall gcubed and then to install the new version. If you do that, be careful again to be in the same directory as the whl file when running pip.

## Second option: Just use the teaching model that matches to python gcubed 1.0.3.

Here is a link to that previous version of the teaching model distribution:

[model_2R_170logv7.zip](https://github.com/McKibbin-Software-Group/issues/files/12363848/model_2R_170logv7.zip)

**Comment by Nelu-LK** [comment]
Hi Geoff,

Thank you for your response. I will try these options out and get back to you if I come across any issues.

Best Regards
Nelu
